@DOC_TITLE@
Xmega Application Note
twi_slave_driver.c File Reference
XMEGA TWI slave driver source file.
#include "twi_slave_driver.h"
#include "clksys_driver.h"
Functions
void TWI_process (TWI_Slave_t *twi)
Process TWI command.
static void TWI_SlaveAddressMatchHandler (TWI_Slave_t *twi)
TWI address match interrupt handler.
static void TWI_SlaveDataHandler (TWI_Slave_t *twi)
TWI data interrupt handler.
void TWI_SlaveInitializeDriver (TWI_Slave_t *twi, TWI_t *module, void(*processDataFunction)(void))
Initalizes TWI slave driver structure.
void TWI_SlaveInitializeModule (TWI_Slave_t *twi, uint8_t address, TWI_SLAVE_INTLVL_t intLevel)
Initialize the TWI module.
static void TWI_SlaveReadHandler (TWI_Slave_t *twi)
TWI slave read interrupt handler.
static void TWI_SlaveStopHandler (TWI_Slave_t *twi)
TWI stop condition interrupt handler.
static void TWI_SlaveTransactionFinished (TWI_Slave_t *twi, uint8_t result)
TWI transaction finished function.
static void TWI_SlaveWriteHandler (TWI_Slave_t *twi)
TWI slave write interrupt handler.
Variables
uint8_t twi_data
uint8_t twic_data_reg
uint8_t twic_status_reg
Detailed Description
XMEGA TWI slave driver source file.
Application note:
AVR1320: True 400kHz operation for TWI slave
Documentation
For comprehensive code documentation, supported compilers, compiler settings and supported devices see readme.html
Author:
Atmel Corporation: http://www.atmel.com
Support email: avr@atmel.com
Copyright (c) 2009 Atmel Corporation. All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
3. The name of Atmel may not be used to endorse or promote products derived from this software without specific prior written permission.
4. This software may only be redistributed and used in connection with an Atmel AVR product.
THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT ARE EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file twi_slave_driver.c.
Function Documentation
void TWI_process (TWI_Slave_t * twi)
Process TWI command.
This function is called out of ISR to process TWI command.
Parameters:
twi The TWI_Slave_t struct instance.
< Clear ACKACT
Definition at line 116 of file twi_slave_driver.c.
References TWI_Slave::bytesReceived, TWI_Slave::bytesSent, TWI_Slave::interface, TWI_Slave::result, TWI_Slave::status, TWI_SlaveAddressMatchHandler(), TWI_SlaveDataHandler(), TWI_SlaveStopHandler(), TWI_SlaveTransactionFinished(), twic_status_reg, TWIS_RESULT_BUS_ERROR, TWIS_RESULT_FAIL, TWIS_RESULT_TRANSMIT_COLLISION, and TWIS_STATUS_READY.
Referenced by ISR().
{
   //static uint8_t sent_NACK = 0;      //!< Holds whether NACK has been transmitted
   uint8_t currentStatus;
   currentStatus = twic_status_reg;
   twi->interface->SLAVE.CTRLB &= ~TWI_SLAVE_ACKACT_bm;
   /* If bus error. */
   if (currentStatus & TWI_SLAVE_BUSERR_bm) {
      twi->bytesReceived = 0;
      twi->bytesSent = 0;
      twi->result = TWIS_RESULT_BUS_ERROR;
      twi->status = TWIS_STATUS_READY;
   }
   else if (currentStatus & TWI_SLAVE_COLL_bm) {
      /* If transmit collision. */
      twi->bytesReceived = 0;
      twi->bytesSent = 0;
      twi->result = TWIS_RESULT_TRANSMIT_COLLISION;
      twi->status = TWIS_STATUS_READY;
   }
   else if ((currentStatus & TWI_SLAVE_APIF_bm) && (currentStatus & TWI_SLAVE_AP_bm)) {
      /* If address match. */
      TWI_SlaveAddressMatchHandler(twi);
   }
   else if (currentStatus & TWI_SLAVE_APIF_bm) {
      /* If stop (only enabled through slave read transaction). */
      TWI_SlaveStopHandler(twi);
   }
   else if (currentStatus & TWI_SLAVE_DIF_bm) {
      /* If data interrupt. */
      TWI_SlaveDataHandler(twi);
   }
   else {
      /* If unexpected state. */
      TWI_SlaveTransactionFinished(twi, TWIS_RESULT_FAIL);
   }
}
static void TWI_SlaveAddressMatchHandler (TWI_Slave_t * twi) [static]
TWI address match interrupt handler.
Prepares TWI module for transaction when an address match occures.
Parameters:
twi The TWI_Slave_t struct instance.
Definition at line 162 of file twi_slave_driver.c.
References TWI_Slave::bytesReceived, TWI_Slave::bytesSent, TWI_Slave::interface, TWI_Slave::result, TWI_Slave::sendData, TWI_Slave::status, twic_data_reg, TWIS_RESULT_UNKNOWN, and TWIS_STATUS_BUSY.
Referenced by TWI_process().
{
   twi->status = TWIS_STATUS_BUSY;
   twi->result = TWIS_RESULT_UNKNOWN;
   /* Disable stop interrupt. */
   uint8_t currentCtrlA = twi->interface->SLAVE.CTRLA;
   twi->interface->SLAVE.CTRLA = currentCtrlA & ~TWI_SLAVE_PIEN_bm;
   twi->bytesReceived = 0;
   twi->bytesSent = 0;
   //init second byte to write
   twic_data_reg = twi->sendData[0];
}
static void TWI_SlaveDataHandler (TWI_Slave_t * twi) [static]
TWI data interrupt handler.
Calls the appropriate slave read or write handler.
Parameters:
twi The TWI_Slave_t struct instance.
Definition at line 199 of file twi_slave_driver.c.
References TWI_SlaveReadHandler(), TWI_SlaveWriteHandler(), and twic_status_reg.
Referenced by TWI_process().
{
   if (twic_status_reg & TWI_SLAVE_DIR_bm) {
      TWI_SlaveWriteHandler(twi);
   } else {
      TWI_SlaveReadHandler(twi);
   }
}
void TWI_SlaveInitializeDriver (TWI_Slave_t * twi, TWI_t * module, void(*)(void) processDataFunction)
Initalizes TWI slave driver structure.
Initialize the instance of the TWI Slave and set the appropriate values.
Parameters:
twi The TWI_Slave_t struct instance.
module Pointer to the TWI module.
processDataFunction Pointer to the function that handles incoming data.
Definition at line 68 of file twi_slave_driver.c.
References TWI_Slave::abort, TWI_Slave::bytesReceived, TWI_Slave::bytesSent, CLKSYS_Disable(), CLKSYS_Enable, CLKSYS_IsReady, CLKSYS_Main_ClockSource_Select(), TWI_Slave::interface, TWI_Slave::Process_Data, TWI_Slave::result, TWI_Slave::status, TWIS_RESULT_UNKNOWN, and TWIS_STATUS_READY.
Referenced by main().
{
   twi->interface = module;
   twi->Process_Data = processDataFunction;
   twi->bytesReceived = 0;
   twi->bytesSent = 0;
   twi->status = TWIS_STATUS_READY;
   twi->result = TWIS_RESULT_UNKNOWN;
   twi->abort = false;
   CLKSYS_Enable( OSC_RC32MEN_bm );
   do {} while ( CLKSYS_IsReady( OSC_RC32MRDY_bm ) == 0 );
   /* 32MHz Internal RC*/
   CLKSYS_Main_ClockSource_Select( CLK_SCLKSEL_RC32M_gc );
   CLKSYS_Disable( OSC_RC2MEN_bm | OSC_RC32KEN_bm );
}
void TWI_SlaveInitializeModule (TWI_Slave_t * twi, uint8_t address, TWI_SLAVE_INTLVL_t intLevel)
Initialize the TWI module.
Enables interrupts on address recognition and data available. Remember to enable interrupts globally from the main application.
Parameters:
twi The TWI_Slave_t struct instance.
address Slave address for this module.
intLevel Interrupt level for the TWI slave interrupt handler.
Definition at line 99 of file twi_slave_driver.c.
References TWI_Slave::interface.
Referenced by main().
{
   twi->interface->SLAVE.CTRLA = intLevel |
                                 TWI_SLAVE_DIEN_bm |
                                 TWI_SLAVE_APIEN_bm |
                                 TWI_SLAVE_ENABLE_bm;
   twi->interface->SLAVE.ADDR = (address<<1);
}
static void TWI_SlaveReadHandler (TWI_Slave_t * twi) [static]
TWI slave read interrupt handler.
Handles TWI slave read transactions and responses.
Parameters:
twi The TWI_Slave_t struct instance.
Definition at line 214 of file twi_slave_driver.c.
References TWI_Slave::bytesReceived, TWI_Slave::interface, TWI_Slave::Process_Data, TWI_Slave::receivedData, twic_data_reg, and TWIS_RECEIVE_BUFFER_SIZE.
Referenced by TWI_SlaveDataHandler().
{
   /* Enable stop interrupt. */
   uint8_t currentCtrlA = twi->interface->SLAVE.CTRLA;
   twi->interface->SLAVE.CTRLA = currentCtrlA | TWI_SLAVE_PIEN_bm;
   /* If free space in buffer.*/
   if (twi->bytesReceived < TWIS_RECEIVE_BUFFER_SIZE) {
      /* Fetch data */
      uint8_t data = twic_data_reg;
      twi->receivedData[twi->bytesReceived] = data;
      /* Process data. */
      twi->Process_Data();
      twi->bytesReceived++;
   } else {
      // We will ignore the overshooting packets.
   }
   /* buffer overflow next time*/
   if  (!(twi->bytesReceived < TWIS_RECEIVE_BUFFER_SIZE)){
      twi->interface->SLAVE.CTRLB |= TWI_SLAVE_ACKACT_bm;
  }
}
static void TWI_SlaveStopHandler (TWI_Slave_t * twi) [static]
TWI stop condition interrupt handler.
Parameters:
twi The TWI_Slave_t struct instance.
Definition at line 182 of file twi_slave_driver.c.
References TWI_Slave::interface, TWI_SlaveTransactionFinished(), and TWIS_RESULT_OK.
Referenced by TWI_process().
{
   /* Disable stop interrupt. */
   uint8_t currentCtrlA = twi->interface->SLAVE.CTRLA;
   twi->interface->SLAVE.CTRLA = currentCtrlA & ~TWI_SLAVE_PIEN_bm;
   uint8_t currentStatus = twi->interface->SLAVE.STATUS;
   twi->interface->SLAVE.STATUS = currentStatus | TWI_SLAVE_APIF_bm;
   TWI_SlaveTransactionFinished(twi, TWIS_RESULT_OK);
}
static void TWI_SlaveTransactionFinished (TWI_Slave_t * twi, uint8_t result) [static]
TWI transaction finished function.
Prepares module for new transaction.
Parameters:
twi The TWI_Slave_t struct instance.
result The result of the transaction.
Definition at line 274 of file twi_slave_driver.c.
References TWI_Slave::result, TWI_Slave::status, and TWIS_STATUS_READY.
Referenced by TWI_process(), TWI_SlaveStopHandler(), and TWI_SlaveWriteHandler().
{
   twi->result = result;
   twi->status = TWIS_STATUS_READY;
}
static void TWI_SlaveWriteHandler (TWI_Slave_t * twi) [static]
TWI slave write interrupt handler.
Handles TWI slave write transactions and responses.
Parameters:
twi The TWI_Slave_t struct instance.
Definition at line 245 of file twi_slave_driver.c.
References TWI_Slave::bytesSent, TWI_Slave::sendData, TWI_SlaveTransactionFinished(), twic_data_reg, twic_status_reg, TWIS_RESULT_BUFFER_OVERFLOW, TWIS_RESULT_OK, and TWIS_SEND_BUFFER_SIZE.
Referenced by TWI_SlaveDataHandler().
{
   /* If NACK, slave write transaction finished. */
   if ((twi->bytesSent > 0) && (twic_status_reg & TWI_SLAVE_RXACK_bm)) {
      //init first byte to write
      twic_data_reg = twi->sendData[0];
      TWI_SlaveTransactionFinished(twi, TWIS_RESULT_OK);
   }
   /* If ACK, master expects more data. */
   else {
      if (twi->bytesSent < TWIS_SEND_BUFFER_SIZE) {
         twi->bytesSent++;
         uint8_t data = twi->sendData[twi->bytesSent];
         twic_data_reg = data;
      }
      else {
         /* If buffer overflow. */
         TWI_SlaveTransactionFinished(twi, TWIS_RESULT_BUFFER_OVERFLOW);
      }
   }
}
Variable Documentation
uint8_t twi_data
uint8_t twic_data_reg
Definition at line 60 of file twi_example.c.
Referenced by TWI_SlaveAddressMatchHandler(), TWI_SlaveReadHandler(), TWI_SlaveWriteHandler(), and TWIC_SlaveProcessData().
uint8_t twic_status_reg
Definition at line 57 of file twi_example.c.
Referenced by TWI_process(), TWI_SlaveDataHandler(), and TWI_SlaveWriteHandler().