@DOC_TITLE@
Xmega Application Note
twi_example.c File Reference
XMEGA TWI slave example source file.
#include "avr_compiler.h"
#include "twi_slave_driver.h"
Defines
#define NUM_BYTES 8
#define SLAVE_ADDRESS 0x51
Functions
ISR (PORTC_INT0_vect)
int main (void)
void TWI_process (TWI_Slave_t *twi)
Process TWI command.
void TWIC_SlaveProcessData (void)
Variables
uint8_t twic_ctrla_reg
uint8_t twic_ctrlb_reg
uint8_t twic_data_reg
uint8_t twic_status_reg
TWI_Slave_t twiSlave
Detailed Description
XMEGA TWI slave example source file.
Application note:
AVR1320: True 400kHz operation for TWI slave
Documentation
For comprehensive code documentation, supported compilers, compiler settings and supported devices see readme.html
Author:
Atmel Corporation: http://www.atmel.com
Support email: avr@atmel.com
Copyright (c) 2009 Atmel Corporation. All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
3. The name of Atmel may not be used to endorse or promote products derived from this software without specific prior written permission.
4. This software may only be redistributed and used in connection with an Atmel AVR product.
THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT ARE EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file twi_example.c.
Define Documentation
#define NUM_BYTES 8
Defining number of bytes in buffer.
Definition at line 67 of file twi_example.c.
#define SLAVE_ADDRESS 0x51
Defining an example slave address.
ATxmega128A1 TWI address
Definition at line 64 of file twi_example.c.
Referenced by main().
Function Documentation
ISR (PORTC_INT0_vect)
/brief TWI Slave Process Data Interrupt
ISR to process TWI
Definition at line 129 of file twi_example.c.
References TWI_process().
{
   PORTC.INTFLAGS |= PORT_INT0IF_bm;
   PORTC.INTCTRL = PORT_INT0LVL_OFF_gc;
   TWI_process(&twiSlave);
}
int main (void)
/brief main function
Example code of TWI application in slave mode with no clock stretching at 400kHz. The data received from the master are stored in receive buffer and then copied in send buffer.
Definition at line 95 of file twi_example.c.
References SLAVE_ADDRESS, TWI_SlaveInitializeDriver(), TWI_SlaveInitializeModule(), and TWIC_SlaveProcessData().
{
   /* Initialize PORTF for debug on STK600 */
   PORTF.DIRSET = 0xFF;
   // Configure LEDs for STK600
   PORTCFG.MPCMASK = 0xFF; // Configure several PINxCTRL registers at the same time
   PORTF.PIN0CTRL = PORT_INVEN_bm; // Invert input to turn the leds on when port output value is 1
   PORTF.OUT = 0x00;
   /* Set up interrupt mask on SCL pin */
   PORTC.INT0MASK = PIN1_bm;
   /* Initialize TWI slave. */
   TWI_SlaveInitializeDriver(&twiSlave, &TWIC, TWIC_SlaveProcessData);
   TWI_SlaveInitializeModule(&twiSlave,
                             SLAVE_ADDRESS,
                             TWI_SLAVE_INTLVL_HI_gc);
   TWIC.SLAVE.CTRLA |= TWI_SLAVE_SMEN_bm;
   /* interrupt level. */
   PMIC.CTRL |= PMIC_HILVLEN_bm | PMIC_MEDLVLEN_bm;
   sei();
   do{
      //User application
   }while (1);
}
void TWI_process (TWI_Slave_t * twi)
Process TWI command.
This function is called out of ISR to process TWI command.
Parameters:
twi The TWI_Slave_t struct instance.
< Clear ACKACT
Definition at line 116 of file twi_slave_driver.c.
References TWI_Slave::bytesReceived, TWI_Slave::bytesSent, TWI_Slave::interface, TWI_Slave::result, TWI_Slave::status, TWI_SlaveAddressMatchHandler(), TWI_SlaveDataHandler(), TWI_SlaveStopHandler(), TWI_SlaveTransactionFinished(), twic_status_reg, TWIS_RESULT_BUS_ERROR, TWIS_RESULT_FAIL, TWIS_RESULT_TRANSMIT_COLLISION, and TWIS_STATUS_READY.
Referenced by ISR().
{
   //static uint8_t sent_NACK = 0;      //!< Holds whether NACK has been transmitted
   uint8_t currentStatus;
   currentStatus = twic_status_reg;
   twi->interface->SLAVE.CTRLB &= ~TWI_SLAVE_ACKACT_bm;
   /* If bus error. */
   if (currentStatus & TWI_SLAVE_BUSERR_bm) {
      twi->bytesReceived = 0;
      twi->bytesSent = 0;
      twi->result = TWIS_RESULT_BUS_ERROR;
      twi->status = TWIS_STATUS_READY;
   }
   else if (currentStatus & TWI_SLAVE_COLL_bm) {
      /* If transmit collision. */
      twi->bytesReceived = 0;
      twi->bytesSent = 0;
      twi->result = TWIS_RESULT_TRANSMIT_COLLISION;
      twi->status = TWIS_STATUS_READY;
   }
   else if ((currentStatus & TWI_SLAVE_APIF_bm) && (currentStatus & TWI_SLAVE_AP_bm)) {
      /* If address match. */
      TWI_SlaveAddressMatchHandler(twi);
   }
   else if (currentStatus & TWI_SLAVE_APIF_bm) {
      /* If stop (only enabled through slave read transaction). */
      TWI_SlaveStopHandler(twi);
   }
   else if (currentStatus & TWI_SLAVE_DIF_bm) {
      /* If data interrupt. */
      TWI_SlaveDataHandler(twi);
   }
   else {
      /* If unexpected state. */
      TWI_SlaveTransactionFinished(twi, TWIS_RESULT_FAIL);
   }
}
void TWIC_SlaveProcessData (void)
/brief Process data from master
Simple function that invert the received value in the sendbuffer. This function is used in the driver and passed on as a pointer to the driver.
Definition at line 77 of file twi_example.c.
References TWI_Slave::bytesReceived, TWI_Slave::receivedData, TWI_Slave::sendData, and twic_data_reg.
Referenced by main().
{
   PORTF.OUT=twiSlave.receivedData[twiSlave.bytesReceived];
   uint8_t recvData = twiSlave.receivedData[twiSlave.bytesReceived];
   twiSlave.sendData[twiSlave.bytesReceived] = recvData;
   //init first byte to write
   twic_data_reg =  twiSlave.sendData[0];
}
Variable Documentation
uint8_t twic_ctrla_reg
Definition at line 58 of file twi_example.c.
uint8_t twic_ctrlb_reg
Definition at line 59 of file twi_example.c.
uint8_t twic_data_reg
Definition at line 60 of file twi_example.c.
Referenced by TWI_SlaveAddressMatchHandler(), TWI_SlaveReadHandler(), TWI_SlaveWriteHandler(), and TWIC_SlaveProcessData().
uint8_t twic_status_reg
Definition at line 57 of file twi_example.c.
Referenced by TWI_process(), TWI_SlaveDataHandler(), and TWI_SlaveWriteHandler().
TWI_Slave_t twiSlave
TWI slave module.
Definition at line 70 of file twi_example.c.