@DOC_TITLE@
Xmega Application Note
event_system_driver.h File Reference
Detailed Description
XMEGA Event system driver header file.
This file contains the function prototypes and enumerator definitions for various configuration parameters for the XMEGA Event system driver.
The driver is not intended for size and/or speed critical code. The driver is intended for rapid prototyping and documentation purposes for getting started with the XMEGA Event system.
For size and/or speed critical code, it is recommended to copy the function contents directly into your application instead of making a function call.
Application note:
AVR1001: Getting Started With the XMEGA Event System
Documentation
For comprehensive code documentation, supported compilers, compiler settings and supported devices see readme.html
Author:
Atmel Corporation: http://www.atmel.com
Support email: avr@atmel.com
Revision
1569
Date
2008-04-22 13:03:43 +0200 (ti, 22 apr 2008)
Copyright (c) 2008, Atmel Corporation All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
3. The name of ATMEL may not be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file event_system_driver.h.
#include "avr_compiler.h"
Functions
void EVSYS_ManualTrigger (uint8_t dataMask, uint8_t strobeMask)
This function sets the event data and strobe for a manual event trigger.
bool EVSYS_SetEventChannelFilter (uint8_t eventChannel, EVSYS_DIGFILT_t filterCoefficient)
This function sets the filter parameters for an event channel.
bool EVSYS_SetEventChannelParameters (uint8_t eventChannel, EVSYS_QDIRM_t QDIRM, bool QDIndexEnable, bool QDEnable, EVSYS_DIGFILT_t filterCoefficient)
This function sets the parameters for an event channel.
bool EVSYS_SetEventSource (uint8_t eventChannel, EVSYS_CHMUX_t eventSource)
This function sets the event source for an event channel.
Function Documentation
void EVSYS_ManualTrigger (uint8_t dataMask, uint8_t strobeMask)
This function sets the event data and strobe for a manual event trigger.
This function manually triggers events on the selected channels. The "Manually Generating Events" section in the Xmega manual have a detailed description of the events generated with the different combinations of the bit settings.
Parameters:
dataMask Bit mask for data events on the channel n, where the bit position n correspond to the channel n.
strobeMask Bit mask for strobe on the channel n, where the bit position n correspond to the channel n.
Definition at line 173 of file event_system_driver.c.
{
        /* The datamask register must be set before the strobe register. */
        EVSYS.DATA = dataMask;
        EVSYS.STROBE = strobeMask;
}
bool EVSYS_SetEventChannelFilter (uint8_t eventChannel, EVSYS_DIGFILT_t filterCoefficient)
This function sets the filter parameters for an event channel.
Parameters:
eventChannel The event channel number, range 0-7.
filterCoefficient Filter coefficient for the digital input filter.
Return values:
true if a valid channel was selected.
false if a non-valid channel was selected.
Definition at line 142 of file event_system_driver.c.
Referenced by Example4().
{
        /*  Check if channel is valid and set the pointer offset for the selected
         *  channel and assign the configuration value.
         */
        if (eventChannel < 8) {
                volatile uint8_t * chCtrl;
                chCtrl = &EVSYS.CH0CTRL + eventChannel;
                *chCtrl = filterCoefficient;
                return true;
        } else {
                return false;
        }
}
bool EVSYS_SetEventChannelParameters (uint8_t eventChannel, EVSYS_QDIRM_t QDIRM, bool QDIndexEnable, bool QDEnable, EVSYS_DIGFILT_t filterCoefficient)
This function sets the parameters for an event channel.
Note:
The quadrature decoder is only available on channel 0, 2 and 4.
Parameters:
eventChannel The event channel number, either 0, 2 or 4.
QDIRM Quadrature decoder index recognition mode.
QDIndexEnable Enable quadrature decoder index.
QDEnable Enable Quadrature decoder.
filterCoefficient Filter coefficient for the digital input filter.
Return values:
true if a valid channel was selected.
false if a non-valid channel was selected.
Definition at line 107 of file event_system_driver.c.
{
        /*  Check if channel is valid and set the pointer offset for the selected
         *  channel and assign the configuration value.
         */
        if ( ( eventChannel == 0 ) ||
             ( eventChannel == 2 ) ||
             ( eventChannel == 4 ) ) {
                volatile uint8_t * chCtrl;
                chCtrl = &EVSYS.CH0CTRL + eventChannel;
                *chCtrl = ( uint8_t ) QDIRM |
                          filterCoefficient |
                          ( QDIndexEnable ? EVSYS_QDIEN_bm : 0 ) |
                          ( QDEnable ? EVSYS_QDEN_bm : 0 );
                return true;
        } else {
                return false;
        }
}
bool EVSYS_SetEventSource (uint8_t eventChannel, EVSYS_CHMUX_t eventSource)
This function sets the event source for an event channel.
Parameters:
eventChannel The event channel number, range 0-7.
eventSource The event source to use as input to the MUX.
Return values:
true if a valid channel was selected.
false if a non-valid channel was selected.
Definition at line 77 of file event_system_driver.c.
Referenced by Example1(), Example2(), Example3(), and Example4().
{
        volatile uint8_t * chMux;
        /*  Check if channel is valid and set the pointer offset for the selected
         *  channel and assign the eventSource value.
         */
        if (eventChannel < 8) {
                chMux = &EVSYS.CH0MUX + eventChannel;
                *chMux = eventSource;
                return true;
        } else {
                return false;
        }
}