@DOC_TITLE@
Xmega Application Note
rtc32_example1.c File Reference
XMEGA 32-bit Real Time Counter (RTC) example source code.
#include "avr_compiler.h"
#include "rtc32_driver.h"
#include "vbat.h"
Functions
void chip_init (void)
int main (void)
__interrupt void rtc32_comp (void)
void vbat_init (void)
Detailed Description
XMEGA 32-bit Real Time Counter (RTC) example source code.
This file contains an example application that demonstrates the 32-bit RTC driver. It shows how to set up the 32-bit RTC together with battery backup module. It uses the compare match interrupt of 32-bit RTC module to wake up MCU from power save mode. This example can be used to demonstrate how low power consumption xmega can be.
Application note:
AVR1321: Using the XMEGA 32-bit RTC
Documentation
For comprehensive code documentation, supported compilers, compiler settings and supported devices see readme.html
Author:
Atmel Corporation: http://www.atmel.com
Support email: avr@atmel.com
Revision
112
Date
2009-11-18 14:31:39 +0800 (WED, 18 Nov 2009)
Definition in file rtc32_example1.c.
Function Documentation
void chip_init (void)
Definition at line 65 of file rtc32_example1.c.
References ENTER_CRITICAL_REGION, and LEAVE_CRITICAL_REGION.
Referenced by main().
{
        /*
        * Disable all modules except the 32-bit RTC to minimise power
        * consumption
        */
        PR.PRGEN = PR_AES_bm | PR_EBI_bm | PR_EVSYS_bm | PR_DMA_bm;
        PR.PRPA = PR_ADC_bm | PR_AC_bm;
        PR.PRPB = PR_DAC_bm | PR_ADC_bm | PR_AC_bm;
        PR.PRPC = PR_TWI_bm | PR_USART0_bm | PR_USART1_bm | PR_SPI_bm
                | PR_HIRES_bm | PR_TC0_bm | PR_TC1_bm;
        PR.PRPD = PR_USART0_bm | PR_USART1_bm | PR_SPI_bm | PR_HIRES_bm
                | PR_TC0_bm | PR_TC1_bm;
        PR.PRPE = PR_TWI_bm | PR_USART0_bm | PR_HIRES_bm | PR_TC0_bm | PR_TC1_bm;
        PR.PRPF = PR_USART0_bm | PR_HIRES_bm | PR_TC0_bm;
        PORTA.DIR = 0x02;
        PORTA.OUTCLR = 0x02;
        /* Configure system clock to use 32 MHz internal RC oscillator */
        OSC.CTRL |= OSC_RC32MEN_bm;
        ENTER_CRITICAL_REGION( );
        CCP = 0xD8;
        CLK.PSCTRL = (uint8_t)CLK_PSADIV_1_gc | (uint8_t)CLK_PSBCDIV_1_1_gc;
        while ( (OSC.STATUS & OSC_RC32MRDY_bm) == 0 );
        CCP = 0xD8;
        CLK.CTRL = CLK_SCLKSEL_RC32M_gc;
        LEAVE_CRITICAL_REGION();
        /* Configure the interrupt system */
        PMIC.CTRL |= PMIC_LOLVLEN_bm;
}
int main (void)
Definition at line 107 of file rtc32_example1.c.
References chip_init(), RTC32_SetAlarm(), RTC32_SetCompareIntLevel(), vbat_init(), VBAT_STATUS_BBBOD, VBAT_STATUS_BBPOR, VBAT_STATUS_NO_POWER, VBAT_STATUS_OK, VBAT_STATUS_XOSCFAIL, and vbat_system_check().
{
        uint8_t vbat_status;
        chip_init();
        vbat_status = vbat_system_check(true);
        /*
        * Depending on the VBAT system check appropriate actions need to
        * be taken.
        * In this example we re-initialize the VBAT system in all
        * error cases.
        */
        switch (vbat_status)
        {
        case VBAT_STATUS_OK:
                // Interrupts must be re-enabled
                RTC32_SetCompareIntLevel(RTC32_COMPINTLVL_LO_gc);
                break;
        case VBAT_STATUS_NO_POWER: // fall through
        case VBAT_STATUS_BBPOR: // fall through
        case VBAT_STATUS_BBBOD: // fall through
        case VBAT_STATUS_XOSCFAIL: // fall through
        default:
                vbat_init();
                break;
        }
        sei();
        while (true) {
                RTC32_SetAlarm(2);
                PORTA.OUTTGL = 0x02;
                SLEEP.CTRL = SLEEP_SMODE_PSAVE_gc | SLEEP_SEN_bm;
                cpu_sleep();
        }
}
__interrupt void rtc32_comp (void)
Definition at line 146 of file rtc32_example1.c.
{
}
void vbat_init (void)
Definition at line 99 of file rtc32_example1.c.
References RTC32_Initialize(), RTC32_SetCompareIntLevel(), vbat_enable_xosc(), and vbat_reset().
Referenced by main().
{
        vbat_reset();
        vbat_enable_xosc(0);
        RTC32_Initialize(0xffffffff, 0, 2 );
        RTC32_SetCompareIntLevel(RTC32_COMPINTLVL_LO_gc);
}